### ISSUE TITLE
Non specific h4 styling with !important rule causes styling issues

### ISSUE THREAD

**Issue by madebyjero** [AlexKvazos/VanillaToasts#8]
Vanilla toasts is styling generic h4 tag with !important which can cause unintended styling issues throughout any website.

I am willing to fix this, since its quite a quick fix

``` CSS
#vanillatoasts-container p, h4 {
  margin: 3px 0!important;
}
```
